# This is a basic workflow to help you get started with Actions

name: "Godot Export HTML5"

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:

env:
  GODOT_VERSION: 3.4.2
  EXPORT_NAME: godot-learn

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  export-html5:
    name: HTML5 Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: HTML5 Build
        run: |
          mkdir -v -p build/web
          cd $EXPORT_NAME
          godot -v --export "HTML5" ../build/web/index.html
      # Install rsync in order to use deploy to GitHub Pages Action from the store
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/web # The folder the action should deploy.